CREATE TABLE topic(
	id UUID NOT NULL PRIMARY KEY,
	title VARCHAR(120) NOT NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT NULL
);

CREATE TABLE post(
	id UUID NOT NULL PRIMARY KEY,
	content VARCHAR(300) NOT NULL,
	topic_id UUID NOT NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT NULL,
	CONSTRAINT fk_topic FOREIGN KEY(topic_id) REFERENCES topic(id)
);